<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PackageId>CSArgParse</PackageId>
    <Version>1.0.0</Version>
    <Authors>Michał Marszałek</Authors>
    <Description>A .NET argument parsing library</Description>
    <PackageProjectUrl>https://github.com/mmpyro/cs-argparse</PackageProjectUrl>
    <RepositoryUrl>https://github.com/mmpyro/cs-argparse</RepositoryUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>
</Project>
